# Generated by Django 4.2.27 on 2025-12-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(verbose_name='Previsão devolução'),
        ),
    ]
